# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pie-rails 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "pie-rails"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kristian Mandrup", "Akshaya Kumar Sharma"]
  s.date = "2014-10-03"
  s.description = "Use PIE in your Rails apps :)"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/pie-rails.rb",
    "pie-rails.gemspec",
    "spec/pie-rails_spec.rb",
    "spec/spec_helper.rb",
    "vendor/assets/javascripts/PIE.htc",
    "vendor/assets/javascripts/PIE_IE678.js",
    "vendor/assets/javascripts/PIE_IE678_uncompressed.js",
    "vendor/assets/javascripts/PIE_IE9.js",
    "vendor/assets/javascripts/PIE_IE9_uncompressed.js",
    "vendor/assets/javascripts/PIE_uncompressed.htc"
  ]
  s.homepage = "http://css3pie.com/"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.2"
  s.summary = "Progressive Internet Explorer (PIE) ready for use with Rails asset pipeline"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

